config/routes.rb
Rails.application.routes.draw do
  get 'landing_page/tetris'
  devise_for :users
  root to: "products#index"
  resources :users, only: [:index, :show] do
    member do
      post :follow
      post :unfollow
      post :remove_follower
    end
    get :follows, on: :member
  end

  resources :products, only: [:index, :show, :new, :create] do
    member do
      post :bookmark
      post :unbookmark
    end

    member do
      get :comments
    end

    resources :comments, only: [:create] do
      member do
        get :replies, as: :comment_replies
      end
    end




  end


  resources :lists, only: [:show, :new, :create]


  get 'welcome', to: 'welcome#show'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :lists, dependent: :destroy

  has_many :products, through: :lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_products, through: :bookmarks, source: :product

  has_many :comments


  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def remove_follower(user_id)
    follower_relationships.find_by(follower_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    relationship ? true : false
  end

  def follows
    @user = User.find(params[:id])
    @followers = @user.followers
    @following = @user.following
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :follow, :unfollow, :follows, :remove_follower, :bookmark, :unbookmark]

  def index
    @users = User.where.not(id: current_user.id)
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js { render action: :follow }
      end
    end
  end

  def remove_follower
    if current_user.remove_follower(@user.id)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    end
  end

  def show
    @lists = @user.lists
  end

  def follows
    @followers = @user.followers
    @following = @user.following
  end


  def bookmark
    if current_user.bookmark(params[:product_id])
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    end
  end

  def unbookmark
    if current_user.unbookmark(params[:product_id])
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js { render action: :bookmark }
      end
    end
  end



  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<li data-user=<%= user.id %>>
  <%= user.username %>
  <% if current_user.is_following?(user.id) %>
    <%= link_to "Unfollow", unfollow_user_path(user.id), method: :post, remote: true %>
  <% else %>
    <%= link_to "Follow", follow_user_path(user.id), method: :post, remote: true %>
  <% end %>
</li>

app/views/users/follow.js.erb
<%# REDUNTANT CODE ??%>

function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.outerHTML = userHTML;
}

renderUser('<%= j render @user %>');

app/views/users/follows.html.erb
<div class="container follows-container bg-white">

  <div class="tab-bar d-flex justify-content-center px-3 py-1">
    <ul class="nav nav-pills mb-2" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active product-tabs" id="pills-followers-tab" data-bs-toggle="pill" data-bs-target="#pills-followers" type="button" role="tab" aria-controls="pills-followers" aria-selected="true">Followers</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link product-tabs" id="pills-following-tab" data-bs-toggle="pill" data-bs-target="#pills-following" type="button" role="tab" aria-controls="pills-following" aria-selected="false">Following</button>
      </li> 
    </ul>
  </div>


  <div class="tab-content product-content" id="pills-tabContent">

    <div class="tab-pane fade show active" id="pills-followers" role="tabpanel" aria-labelledby="pills-followers-tab">
      <% @followers.each do |user| %>
        <div class="follow-bar d-flex justify-content-between align-items-center mb-3 w-100">
          <div class="follow-bar__content-container align-items-center d-flex">
            <%= link_to user_path(user) do %>
              <%= cl_image_tag user.avatar.key, crop: "fill", gravity: "center", aspect_ratio: "1:1", class: "avatar" %>
            <% end %>
            <div class="d-flex flex-column justify-content-center mx-2">
              <div class="d-flex">
                <span style="font-weight: 700;"><%= user.username %></span>
                <% if current_user.is_following?(user.id) == false && @user == current_user %>
                  <%= button_to 'Follow', follow_user_path(user), method: :post, class: "small-follow" %>
                <% end %>
              </div>
              <div class="follow-bar__user-list-and-products-count", style="font-weight: 400px;">
                <%= user.lists.count %> lists • <%= user.products.count %> products
              </div>
            </div>
          </div>
          <% if @user == current_user %>
            <%= button_to 'Remove', remove_follower_user_path(user), method: :post, class: "btn btn-gray" %>
          <% elsif current_user.is_following?(user.id) %>
            <%= button_to 'Followed', unfollow_user_path(user), method: :post, class: "btn btn-main" %>
          <% elsif user.is_following?(current_user.id) %>
            <%= button_to 'Follow Back', follow_user_path(user), method: :post, class: "btn btn-pink" %>
          <% else %>
            <%= button_to 'Follow', follow_user_path(user), method: :post, class: "btn btn-pink" %>
          <% end %>
        </div>
      <% end %>
    </div>


  <div class="tab-pane fade" id="pills-following" role="tabpanel" aria-labelledby="pills-following-tab">
    <% @following.each do |user| %>
      <div class="follow-bar d-flex justify-content-between align-items-center mb-3 w-100">
        <div class="follow-bar__content-container align-items-center d-flex">
          <%= link_to user_path(user) do %>
            <%= cl_image_tag user.avatar.key, crop: "fill", gravity: "center", aspect_ratio: "1:1", class: "avatar" %>
          <% end %>
          <div class="d-flex flex-column justify-content-center mx-2">
            <div class="d-flex">
              <%= user.username %>
            </div>
            <div class="follow-bar__user-list-and-products-count">
              <%= user.lists.count %> lists • <%= user.products.count %> products
            </div>
          </div>
        </div>
        <% if current_user.is_following?(user.id) %>
          <%= button_to 'Followed', unfollow_user_path(user), method: :post, class: "btn btn-main" %>
        <% else %>
          <%= button_to 'Follow', follow_user_path(user), method: :post, class: "btn btn-pink" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>





</div>

app/views/users/index.html.erb
<h1>Users:</h1>
<ul>
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<div class="container w-100 bg-white user-container setParentControllerForBackLinks" data-controller="history-tracker" data-history-tracker-parent-controller-value="user-show">
  <div class="profile-box d-flex flex-col align-content-center justify-content-center w-100 mx-auto bg-white pt-3">
    <%= cl_image_tag @user.avatar.key, crop: "fill", gravity: "center", aspect_ratio: "1:1", aspect_ratio: "1:1", class: "avatar-xl align-self-center user-img" %>
    <div class="header-text-follow-button w-100 my-1 ml-3">
      <div class="header-and-follow-button d-flex justify-content-between align-items-bottom">
        <h3 class="align-self-end"><%= @user.username %></h3>
        <% if current_user != @user %>
          <% if current_user.is_following?(@user) %>
            <%= link_to unfollow_user_path(@user), method: :delete do %>
              <button class="btn btn-main">Followed</button>
            <% end %>
          <% else %>
            <%= link_to follow_user_path(@user), method: :post do %>
              <button class="btn btn-pink">Follow</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="text">
        <p>
          <%= @user.lists.count %> lists • <%= @user.products.count %> products<br>
          <%= link_to follows_user_path(@user), class: "text-decoration-none text-body ", style: "color: #8E8E8E;" do %>
            <%= @user.followers.count %> followers • <%= @user.following.count %> following
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <div class="tab-bar d-flex justify-content-center py-1" style="font-weight: 100;">
    <ul class="nav nav-pills mb-2" id="pills-tab" role="tablist">

      <li class="nav-item" role="presentation">
        <button class="nav-link active product-tabs" id="pills-lists-tab" data-bs-toggle="pill" data-bs-target="#pills-lists" type="button" role="tab" aria-controls="pills-lists" aria-selected="true">Lists</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link product-tabs" id="pills-bio-tab" data-bs-toggle="pill" data-bs-target="#pills-bio" type="button" role="tab" aria-controls="pills-bio" aria-selected="false">Profile</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link product-tabs" id="pills-referrals-tab" data-bs-toggle="pill" data-bs-target="#pills-referrals" type="button" role="tab" aria-controls="pills-referrals" aria-selected="false">Referrals</button>
      </li>
      <% if @user = current_user %>
        <li class="nav-item" role="presentation">
          <button class="nav-link product-tabs" id="pills-bookmarks-tab" data-bs-toggle="pill" data-bs-target="#pills-bookmarks" type="button" role="tab" aria-controls="pills-bookmarks" aria-selected="false">Bookmarks</button>
        </li>
      <% end %>

    </ul>
  </div>


  <div class="tab-content product-content container w-100 p-0" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-lists" role="tabpanel" aria-labelledby="pills-lists-tab">
      <% @lists.each do |list| %>
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="list-banner d-flex flex-row justify-content-center align-items-center py-3 mb-3"
            <% if list.products.any? && list.products.first.photos.any? %>
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.products.first.photos.first.key %>);"
            <% else %>
              style="background-color: darkgray;"
            <% end %>
            >
            <div class="d-flex flex-column justify-content-center">
              <h3 class="text-center"><%= list.title %></h3>
              <p class="text-center "><%= list.products.count %> products</p>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="d-flex justify-content-center">
        <%= link_to new_list_path, class: "d-flex text-align-center text-decoration-none mt-3" do %>
          <i class="fa-light fa-circle-plus fa-2xl text-decoration-none" style="color: #8E8E8E"></i>
        <% end %>
      </div>
    </div>

    <div class="tab-pane fade" id="pills-bio" role="tabpanel" aria-labelledby="pills-bio-tab">
      <%= @user.username %>
    </div>

    <div class="tab-pane fade" id="pills-referrals" role="tabpanel" aria-labelledby="pills-referrals-tab">
        <% @user.products.each do |product| %>
          <%= product.referrals %>
        <% end %>
    </div>

    <% if @user == current_user%>
      <div class="tab-pane fade" id="pills-bookmarks" role="tabpanel" aria-labelledby="pills-bookmarks-tab">
      <% if @user.bookmarked_products.exists?%>
        <%= render "shared/products", products: @user.bookmarked_products, current_path: request.path %>
      <% else %>
        <div class="d-flex justify-content-center">
          <h5 class="text-center">No bookmarks yet</h5>
        </div>
      <% end %>
      </div>
    <% end %>

  </div>




<!--

<%# VINCE CODE old rectangle%>


<% @lists.each do |list| %>
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="list-banner d-flex flex-row justify-content-center align-items-center py-3 mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
            <div class="d-flex flex-column justify-content-center">
              <h4 class="text-center"><%= list.title %></h4>
              <p class="text-center"><%= list.products.count %> products</p>
            </div>
          </div>
        <% end %>
      <% end %>

<%# VINCE CODE ß possible grid solution %>



  <% @lists.each do |list| %>
    <%= link_to list_path(list), class: "text-decoration-none" do %>
      <div class="list-banner d-flex flex-row justify-content-center align-items-center py-3 mb-3">
        <div class="list-grid-8">
          <%= generate_tiled_background(list) %>
          <div class="d-flex flex-column justify-content-center list-content">
            <h4 class="text-center"><%= list.title %></h4>
            <p class="text-center"><%= list.products.count %> products</p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

-->







</div>