config/routes.rb
Rails.application.routes.draw do
  get 'landing_page/tetris'
  devise_for :users
  root to: "products#index"
  resources :users, only: [:index, :show] do
    member do
      post :follow
      post :unfollow
      post :remove_follower
    end
    get :follows, on: :member
  end

  resources :products, only: [:index, :show, :new, :create] do
    member do
      post :bookmark
      post :unbookmark
    end

    member do
      get :comments
    end

    resources :comments, only: [:create] do
      member do
        get :replies, as: :comment_replies
      end
    end




  end


  resources :lists, only: [:show, :new, :create]


  get 'welcome', to: 'welcome#show'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-bs-autohide="true" data-bs-delay="3000">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-bs-autohide="true" data-bs-delay="3000">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_menu.html.erb
<div class="container justify-content-evenly d-flex py-3 menu">
  <%= link_to products_path do %>
    <i class="fa-light fa-house-blank"></i>
  <% end %>

  <%= link_to user_path(current_user) do %>
    <i class="fa-light fa-user"></i>
  <% end %>

  <%= link_to new_product_path do %>
    <i class="fa-light fa-plus"></i>
  <% end %>

  <%= link_to welcome_path do %>
    <%= image_tag("https://res.cloudinary.com/dncij7vr6/image/upload/v1679021812/Group_6_2_b5srbk.png", style: "width: 20px; height: 20px;") %>

  <% end %>
</div>


<%# <i class="fa-light fa-list"></i> %>

app/views/shared/_product.html.erb
<div class="product-header d-flex justify-content-start flex-row px-3">

  <% if params[:controller] == "products" && params[:action] == "show" %>
    <%= link_to "", data: {controller: "back-link", back_link_target: "link", back_link_list_value: product.list.id, back_link_user_value: current_user.id} do %>
      <i class="fas fa-arrow-left fa-light text-decoration-none" style="color: #444444;"></i>
    <% end %>
  <% end %>




  <div class="title-and-price mx-auto text-center">
    <% if params[:controller] != "lists" %>
      <%= link_to list_path(product.list), class: "text-decoration-none", style: "color: #444444; font-weight: 100;" do %>
        <%= product.list.title %>
      <% end %>
    <% end %>
    <h3 class="mb-0"> <%= product.title %></h3>
    $<%= number_with_precision(product.price, precision: 0) %>
  </div>
</div>

<div class="product">
  <div id="carouselExampleIndicators<%= product.id %>" class="carousel slide">
    <div class="carousel-indicators">
      <% product.photos.each_with_index do |photo, index| %>
        <button type="button" data-bs-target="#carouselExampleIndicators<%= product.id %>" data-bs-slide-to="<%= index %>" class=<%= "active" if index == 0 %> aria-current="true" aria-label="Slide <%= index %>"></button>
      <% end %>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <% if product.photos.attached? %>
          <%= cl_image_tag product.photos.first.key, crop: :fill, class: "w-100" %>
        <% else %>
          <%= image_tag "https://unsplash.com/photos/hxi_yRxODNc", crop: :fill, class: "w-100" %>
        <% end %>
      </div>
      <% product.photos.drop(1).each do |photo| %>
        <div class="carousel-item">
            <%= cl_image_tag photo.key, crop: :fill, class: "w-100" %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators<%= product.id %>" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators<%= product.id %>" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <div class="container d-flex py-1 px-1.5 justify-content-between align-items-center product-bar">
    <%= link_to user_path(product.user), class: "text-decoration-none d-flex align-items-center" do %>
      <%= cl_image_tag product.user.avatar.key, crop: "fill", gravity: "center", aspect_ratio: "1:1", class: "avatar-xs"%>
      <span style="font-weight: 700; text-decoration: none; color: #444444;"><%=product.user.username%></span>
    <% end %>

    <% if product.logo.attached? %>
      <%= cl_image_tag product.logo.key, crop: :fill, class: "logo container" %>
    <% else %>
      <%= image_tag "https://unsplash.com/photos/hxi_yRxODNc", crop: :fill, class: "logo container" %>
    <% end %>

    <div class="product-icon-buttons d-flex justify-content-center align-items-center">
      <%= link_to product_comments_path(product), class: 'no-style-button' do %>
        <i class="fa-light fa-comment fa-lg"></i>
      <% end %>

      <i class="fa-light fa-square-plus fa-lg px-1"></i>

    <% if product.bookmarked_by?(current_user) %>
      <%= link_to unbookmark_product_path(product), method: :post, class: 'no-style-button', data: { controller: 'bookmark', action: 'click->bookmark#toggle', bookmark_target: 'bookmarkbutton' } do %>
        <i class="fa-solid fa-circle-bookmark fa-lg"></i>
      <% end %>
    <% else %>
      <%= link_to bookmark_product_path(product), method: :post, class: 'no-style-button', data: { controller: 'bookmark', action: 'click->bookmark#toggle', bookmark_target: 'bookmarkbutton' } do %>
        <i class="fa-light fa-circle-bookmark fa-lg"></i>
      <% end %>
    <% end %>

    </div>
  </div>
</div>

app/views/shared/_products.html.erb
<div class="container product-container w-100 px-0 bg-white" data-controller="comments">

  <% products.each do |product| %>
    <%= render "shared/product", product: product, locals: { button_class: 'btn btn-main', link_url: product_path(product), link_label: "Read More"} %>
    <%= link_to product_path(product), class: "no-underline" do%>
      <div class="review-box w-100">

        <% if product.review %>
        <p>
          <%= product.review.truncate(157) %>
        </p>
        <% else %>
        <p>
          No review yet.
        </p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>